# Generated by Django 3.1 on 2020-10-25 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='Apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 22, 52, 25, 829227)),
        ),
        migrations.AddField(
            model_name='contacto',
            name='Mensaje',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='Nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='Telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
