# Generated by Django 3.1 on 2020-10-28 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20201024_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='Fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 28, 0, 4, 38, 101152)),
        ),
    ]
