# Generated by Django 3.1 on 2020-11-01 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20201028_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 1, 17, 29, 50, 953713)),
        ),
    ]
