# Generated by Django 3.1 on 2020-11-03 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20201101_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='Fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 22, 13, 6, 889547)),
        ),
    ]
