# Generated by Django 3.1 on 2020-11-03 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20201102_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, null=True)),
                ('Valor', models.CharField(max_length=50, null=True)),
                ('Descripcion', models.CharField(max_length=50, null=True)),
                ('Estado', models.BooleanField(default=True)),
                ('Actualizacion', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 22, 20, 27, 371563))),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 22, 20, 27, 370566)),
        ),
    ]
