# Generated by Django 3.1 on 2020-11-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
